### ISSUE TITLE
Add standard specification on each kayak page

### ISSUE THREAD

**Issue by bokkura-rex** [bokkura-expedition/bokkura.com#10]

**Comment by bokkura-rex** [comment]
Content added, pulle request closed. It doesn't appear on the website yet, what did I forget, or is this the step Yoshi is doing ?

**Comment by jmblog** [comment]
After closing pull request, it takes a few minutes to be changed website. You can check the status with the badge on https://github.com/bokkura-expedition/bokkura.com

![bokkura com 2016-01-08 15-12-07](https://cloud.githubusercontent.com/assets/86085/12191624/44d4bcc2-b61a-11e5-8630-537afd90d9de.png)
